// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © FreedyW

//@version=5
strategy("TradingBot-3.3.3", overlay=true,pyramiding = 20)

//###INPUTS
float nwo = input(high,'Z Shadow')
float plot_ = input(high,'Plot')
sma50 = ta.sma(close,50)
sma200 = ta.sma(close,200)

//###VARIABLES
var float takeProfit = na
var float stopLoss = na
var float longTakeProfit = na
var float longStopLoss = na
var float diff = na
var float onetick = syminfo.mintick
var float nwo1max = na 
var float nwo_1max = na 

var int plotKlesa = 0
var int plotStupa = 0
var int  plus = 0

var bool candleDir = na
var bool sma200gu = na 
var bool sma50gu = na 
var bool nwo_2 = na
var bool nwo2 = na
var bool nwo4 = na 
var bool nwo_4 = na 
var bool plot4 = na 
var bool plot_4 = na 
var bool plot2 = na
var bool plot_2 = na 
var bool nwo1 = na 
var bool nwo_1 = na 
var bool pltGU = na 
var bool pltGD = na 
var bool pltGU0 = na 
var bool pltGD0 = na 
var bool checkSecLong = na 
var bool checkSecShort = na 
var bool long = na 
var bool short = na
var float patdesiat = na 
var float Lpatdesiat = na 
var int sLong = 0
var int kShort = 0
var int celkovo = 0

//###FUNCITONS

//t1 = time(timeframe.period, "0200-0400",'GMT-5')
t1 = time(timeframe.period, "0200-0400")
bgcolor(t1 ? color.rgb(149, 83, 255, 85) : na)

plot(sma50,'sma50',color.blue)
plot(sma200,'sma200',color.yellow)


printTable(txtLeft, txtMiddle,txtRight,percenta) =>
    var table t = table.new(position.middle_right, 3, 2)
    table.cell(t, 0, 0, txtLeft, bgcolor = color.yellow, text_halign = text.align_right)
    table.cell(t, 1, 0, txtMiddle, bgcolor = color.yellow, text_halign = text.align_left)
    table.cell(t, 2, 0, txtRight, bgcolor = color.yellow, text_halign = text.align_left)
    table.cell(t, 1, 1, percenta, bgcolor = color.yellow, text_halign = text.align_left)


//### 8:00 - 10:00
//GetSmaDirections
//GetDiff
if hour == 3 and minute == 45
    candleDir := na
    sma50gu := na 
    sma200gu := na 
    //SMA50
    if sma50 <= (sma50[7] - (onetick*9))
        sma50gu := false

    else if sma50 >= (sma50[7] + (onetick*9))
        sma50gu := true

    else
        sma50gu := na
    //SMA200
    if sma200 < (sma200[7] - (onetick*9))
        sma200gu := false
    else if sma200 > (sma200[7] + (onetick*9))
        sma200gu := true
    else 
        sma200gu := na
    //CandleDir
    if close > open[7]
        candleDir := true

    else
        candleDir := false
    //GetDiff
    max = high
    min = low

    for i = 0 to 7
        accMin = low[i]
        accMax = high[i]
        if accMin<min
            min := accMin
        if accMax > max
            max := accMax

    diff := max - min

//GetNwo 2-4 Plot 3z8
//GetPlot
if hour == 3 and minute == 45
    //GetPlot
    short := na 
    long := na 
    plotStupa := 0
    plotKlesa := 0
    nwo2 := na 
    nwo_2 := na 
    checkSecLong := na 
    checkSecShort := na 
    pltGU := na
    pltGD := na 
    for i = 0 to 7
        if plot_[i+1] < plot_[i]
            plotStupa += 1

        if plot_[i+1] > plot_[i]
            plotKlesa += 1

    if plotKlesa >= 5
        pltGD := true

    if plotStupa >= 5
        pltGU := true


    //GetNwo
    for i = 0 to 7
        //LONG NWO 2 <=> 4
        if nwo[i] >= 2.0 and nwo[i] <= 4.0 and pltGU
            nwo2 := true
        //SHORT NWO -2 <=> -4
        if nwo[i] <= -2.0 and nwo[i] >= -4.0 and pltGD
            nwo_2 := true
            
    //Check if NWO < -5
    for i = 0 to 7
        if nwo[i] > 4.0
            nwo2 := na 

        if nwo[i] < -4.0
            nwo_2 := na 

//###GetNwo 2-4 Plot 0z8
if hour == 3 and minute == 45
    pltGD0 := true
    pltGU0 := true
    for i = 0 to 7

        //long
        if plot_[i] < plot_[i+1]
            pltGU0 := false
   
        //short
        if plot_[i] > plot_[i+1]
            pltGD0 := false

//###GetNwo 4-5
if hour == 3 and minute == 45
    nwo4 := na
    nwo_4 := na 

    for i = 0 to 7
        //Short
        if nwo[i] < -4.0 and nwo[i] > -5.0
            nwo_4 := true
        //Long
        if nwo[i] > 4.0 and nwo[i] < 5.0 
            nwo4 := true
    //Check Nwo < -5 or Nwo > 5
    for i = 0 to 7
        if nwo[i] <= -5.0
            nwo_4 := na 

        if nwo[i] >= 5.0
            nwo4 := na

//###GetNwo 1.7-2
if hour == 3 and minute == 45
    nwo1 := na 
    nwo_1 := na 
    nwo1max := 0 
    nwo_1max := 0 

    for i = 0 to 7
        //Short
        if nwo[i] <= -1.7 and nwo[i] > -2.0
            nwo_1 := true
            //Get Min Nwo Value
            if nwo[i] < nwo_1max
                nwo_1max := nwo[i]
        //Long
        if nwo[i] >= 1.7 and nwo[i] < 2.0
            nwo1 := true
            //Get Max Nwo Value
            if nwo[i] > nwo1max
                nwo1max := nwo[i]

    for i = 0 to 7 
        if nwo[i] <= -2.0
            nwo_1 := na 

        if nwo[i] >= 2.0
            nwo1 := na 



//###10:00+ (2. Phase)
//CHECKING +-2 < NWO < +-4
if nwo <= -2.0 and nwo[1] <= -2.0 and nwo2
    checkSecLong := true

if nwo >= 2.0 and nwo[1] >= 2.0 and nwo_2
    checkSecShort := true

//CHECKING +-2 < NWO < +-4 + Plot 0z8
if nwo <= -2.0 and pltGU0 and nwo2
    checkSecLong := true

if nwo >= 2.0 and pltGD0 and nwo_2
    checkSecShort := true

//CHECKING +-4 < NWO < +-5
if nwo <= -2.0 and nwo[1] <= -2.0 and nwo4 and pltGU
    checkSecLong := true

if nwo >= 2.0 and nwo[1] >= 2.0 and nwo_4 and pltGD
    checkSecShort := true

//CHECKING +-1.7 < NWO > +- 2
if nwo <= (nwo1max* -1) and nwo[1] <= (nwo1max * -1) and pltGU and nwo1
    checkSecLong := true

if nwo >= (nwo_1max * -1) and nwo[1] >= (nwo_1max * -1) and pltGD and nwo_1
    checkSecShort := true

//###3. PHASE
if nwo <= -0.5 and nwo[1] <= -0.5 and plot_ < plot_[1] and plot_[1] < plot_[2] and checkSecShort
    short := true

if nwo >= 0.5 and nwo[1] >= 0.5 and plot_ > plot_[1] and plot_[1] > plot_[2] and checkSecLong
    long := true

//bgcolor(long ? color.orange : na)
//###SHORT
if sma50gu == false and sma200gu == false and candleDir == false and short == true

    takeProfit := close - diff*2
    stopLoss := close + diff
    patdesiat := close - diff 
    strategy.entry("Short"+str.tostring(plus), strategy.short)
    strategy.exit("Short Exit"+str.tostring(plus),from_entry = "Short"+str.tostring(plus),stop = stopLoss , limit = takeProfit)

    alert('67945022097494,sell,' + syminfo.ticker + ',risk=0.30,sl='+str.tostring(stopLoss)+',tp='+str.tostring(takeProfit), alert.freq_once_per_bar_close)

    sma50gu := na
    sma200gu := na
    diff := na
    candleDir := na
    plus += 1
    short := na 
    checkSecShort := na 
    nwo_2 := na 
    pltGD := na 
    celkovo += 1

if low <= patdesiat
    kShort += 1
    patdesiat := na

if low <= takeProfit or high >= stopLoss
    stopLoss   := na
    takeProfit := na
    patdesiat := na 

plot(stopLoss, "SL", color.rgb(255, 0, 0), style = plot.style_circles)
plot(takeProfit, "TP", color.green, style = plot.style_circles)
plot(patdesiat, "PD", color.yellow, style = plot.style_circles)

///###LONG
if sma50gu and sma200gu and candleDir and long
    longTakeProfit := close + diff*2
    longStopLoss := close - diff
    Lpatdesiat := close + diff
    strategy.entry("Long"+str.tostring(plus), strategy.long)
    strategy.exit("Long Exit"+str.tostring(plus),from_entry = "Long"+str.tostring(plus),stop = longStopLoss , limit = longTakeProfit)
    
    alert('67945022097494,buy,' + syminfo.ticker + ',risk=0.30,sl='+str.tostring(longStopLoss)+',tp='+str.tostring(longTakeProfit), alert.freq_once_per_bar_close)

    sma50gu := na
    sma200gu := na
    diff := na
    candleDir := na
    plus += 1
    long := na
    checkSecLong := na 
    nwo2 := na 
    pltGU := na 
    celkovo += 1

if high >= Lpatdesiat 
    sLong += 1
    Lpatdesiat := na 

if low <= longStopLoss or high >= longTakeProfit
    longStopLoss   := na
    longTakeProfit := na
    Lpatdesiat := na 

plot(longStopLoss, "SL", color.red, style = plot.style_circles)
plot(longTakeProfit, "TP", color.green, style = plot.style_circles)
plot(Lpatdesiat, "SL", color.rgb(242, 255, 0), style = plot.style_circles)

printTable(str.tostring(sLong),str.tostring(kShort),str.tostring(celkovo),str.tostring((kShort+sLong)/celkovo))