// This Pine Script™ code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © FreedyW

//@version=5
strategy("TradingBot-5.2_raw", overlay=true,pyramiding = 20,currency="EUR")

// Import ZenLibrary
import ZenAndTheArtOfTrading/ZenLibrary/5 as zen

nwo = input(high,'Z Shadow')
int licenceID = input(67945022097498,'licenceID')
int pipRisk = 3
float maxSpread = input(2.0, 'Max Spread')

float accountBalance  = input(title="Account Balance",  defval=100000.0, group="AutoView Oanda Settings", tooltip="Your Oanda account balance (optional - used for automation through AutoView plugin)")
string accountCurrency = input(title="Account Currency",  defval="EUR" )
float riskPerTrade    = input(title="Risk Per Trade %", defval=.03,  group="AutoView Oanda Settings", tooltip="Your risk per trade as a % of your account balance (optional - used for automation through AutoView plugin)")

float cl = na 
float VOLUME = 1.0
var int plus = 1
float a = na
float b = na
var bool timeshift = true

//------------- DETERMINE POSITION SIZE -------------//
// Check if our account currency is the same as the base or quote currency or neither (for risk $ conversion purposes)
accountSameAsCounterCurrency = strategy.account_currency == syminfo.currency
accountSameAsBaseCurrency = strategy.account_currency == syminfo.basecurrency
accountNeitherCurrency = not accountSameAsCounterCurrency and not accountSameAsBaseCurrency

// Get currency conversion rates if applicable
conversionCurrencyPair = accountSameAsCounterCurrency ? syminfo.tickerid : strategy.account_currency + syminfo.currency
conversionCurrencyRate = accountSameAsBaseCurrency or accountNeitherCurrency ? request.security(conversionCurrencyPair, "D", close, ignore_invalid_symbol=true) : 1.0

// 22:00 - 00:00
t1 = time(timeframe.period, "1600-1800")
bgcolor(t1 ? color.rgb(149, 83, 255, 85) : na)

// Display the current conversion currency ticker (for debug purposes)
if barstate.islastconfirmedhistory
    table t = table.new(position.top_right, 1, 2, color.black)
    table.cell(t, 0, 0, "Conversion: " + conversionCurrencyPair + " (" + str.tostring(conversionCurrencyRate) + ")", text_color=color.white, text_size=size.small)
    table.cell(t, 0, 1, "Account: $" + str.tostring(zen.truncate(strategy.equity)), text_color=color.white, text_size=size.small)

bgcolor(nwo <= -6.0 ? color.rgb(255, 153, 0, 62) : na )

//Open Pos
if nwo <= -6.0 and not t1
    strategy.order(" ",strategy.long,qty = VOLUME)
    strategy.order("  ",strategy.short,qty = VOLUME)
    a := open - 10*syminfo.mintick
    b := open + 200*syminfo.mintick

    VOLUME := zen.av_getPositionSize(accountBalance, riskPerTrade, pipRisk, conversionCurrencyRate)
    VOLUME := VOLUME % 2 ? VOLUME + 1 : VOLUME
    log.info("VOL: {0}",str.tostring(VOLUME))
    VOLUME := VOLUME / 1000000
    log.info("VOL1: {0}",str.tostring(VOLUME))
    alert(str.tostring(licenceID)+',buy,' + syminfo.ticker + ',risk='+str.tostring(VOLUME) + ',spread='+str.tostring(maxSpread) ,alert.freq_once_per_bar_close)

//5
if (nwo[1] <= -6.000 and nwo > -6.0)
    a := open - 10*syminfo.mintick
    b := open + 200*syminfo.mintick

plot(a , "SL", color.rgb(0, 247, 255),linewidth = 1, style = plot.style_circles)
plot(b , "TP", color.rgb(238, 255, 0),linewidth = 1, style = plot.style_circles)
